### ISSUE TITLE
Not working with Sony BRAVIA KDL-32EX710

### ISSUE THREAD

**Issue by pengyver** [masmu/pulseaudio-dlna#101]
Hello,

I've tried to stream to my Sony TV but i've got no sound and these traces :

```
pulseaudio-dlna --disable-ssdp-listener
10-04 11:29:27 pulseaudio_dlna.application                    INFO     Using version: 0.4.5.2
10-04 11:29:27 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.0.14:8080
10-04 11:29:27 pulseaudio_dlna.application                    INFO     Encoder settings:
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <AacEncoder available="True" bit-rate="192">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <FlacEncoder available="True">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <L16Encoder available="True" sample-rate="44100" channels="2">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <LameEncoder available="True" bit-rate="192">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <OggEncoder available="True" bit-rate="192">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <OpusEncoder available="True" bit-rate="192">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <WavEncoder available="True">
10-04 11:29:27 pulseaudio_dlna.application                    INFO     Codec settings:
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav">
10-04 11:29:27 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg">
10-04 11:29:33 pulseaudio_dlna.listener                       INFO     Discovery complete.
10-04 11:29:33 pulseaudio_dlna.pulseaudio                     INFO     Could not get default sink. Perhaps there is no one set?
10-04 11:29:34 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Chromecast8591 (Chromecast)".
10-04 11:29:35 pulseaudio_dlna.pulseaudio                     INFO     Added the device "BRAVIA KDL-32EX710 (DLNA)".
10-04 11:29:35 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink8"
10-04 11:29:36 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink8
10-04 11:29:36 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "BRAVIA KDL-32EX710 (DLNA)" to play ...
10-04 11:29:36 pulseaudio_dlna.streamserver                   INFO     URL settings: /dWRuPXV1aWQ6MDAwMDAwMDAtMDAwMC0xMDEwLTgwMDAtRjBCRjk3NEFBODA4/stream.mp3 (udn=uuid:00000000-0000-1010-8000-F0BF974AA808)
10-04 11:29:36 pulseaudio_dlna.streamserver                   INFO     Got request from 192.168.0.33 - HEAD /dWRuPXV1aWQ6MDAwMDAwMDAtMDAwMC0xMDEwLTgwMDAtRjBCRjk3NEFBODA4/stream.mp3 HTTP/1.1,200,-
10-04 11:29:36 pulseaudio_dlna.plugins.upnp.renderer          ERROR    "BRAVIA KDL-32EX710" registering failed!
10-04 11:29:36 pulseaudio_dlna.pulseaudio                     ERROR    The device "BRAVIA KDL-32EX710 (DLNA)" failed to play! (None)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 580, in _handle_sink_update
    result = future.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 628, in __handle_sink_update
    return_code))
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 500, in switch_back
    name=(self.fallback_sink.label).encode(
AttributeError: 'NoneType' object has no attribute 'label'
```
`
Could you, please, have a look ? I can make tests to help to debug.

**Comment by masmu** [comment]
Hey, could you please provide a full _debug.log_?

```bash
pulseaudio-dlna --debug 2>&1 | tee -a debug.log
```
will create one in the current directory.

**Comment by masmu** [comment]
I fixed the exception in current master, but i am pretty sure this was not the acutal problem.

**Comment by pengyver** [comment]
Hello, effectively i've test the current master and it continues to crash. I've attached a debug file.

**Comment by masmu** [comment]
Thank you for the bug report. There are 2 bugs. One is about a failure during the registering progress. Thats the hard one. For that one to fix i need a wireshark capture of a working registering session. You can do that with every DLNA control application e.g. BubbleUPnP (Android). 
The other one is an encoding error. I will will fix that later.

Am 5. Oktober 2015 09:30:32 MESZ, schrieb pengyver <notifications@github.com>:

**Comment by masmu** [comment]
I think I fixed the second error. But as i said, for the first one I need your help, since i don't own that device myself.

**Comment by masmu** [comment]
Closed due to inactivity.
