### ISSUE TITLE
Fails to connect to Sink

### ISSUE THREAD

**Issue by dehein** [masmu/pulseaudio-dlna#22]
I have a Raspberry Pi with Raspbian, with BubbleUPNP installed.
And when i try to connect. i get these errors:

pulseaudio-dlna
Using localhost: 192.168.1.30:8080
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 192.168.1.44
INFO:root:found upnp_device "<CoinedUpnpMediaRenderer name="" short_name="" state="idle">"
INFO:root:Discovery complete. You can now use your upnp devices!
Fehlgeschlagen: Modulinitialisierung fehlgeschlagen
Traceback (most recent call last):
  File "/usr/bin/pulseaudio-dlna", line 9, in <module>
    load_entry_point('pulseaudio-dlna==0.3.1', 'console_scripts', 'pulseaudio-dlna')()
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/__main__.py", line 147, in main
    pulseaudio_dlna.startup()
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/__main__.py", line 128, in startup
    self.pulse.set_upnp_devices(upnp_devices)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 242, in set_upnp_devices
    self._ensure_bridge(upnp_device)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 247, in _ensure_bridge
    upnp_device.short_name, upnp_device.name)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 121, in create_null_sink
    entity_id = int(subprocess.check_output(cmd))
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'pactl', u'load-module', u'module-null-sink', u'sink_name=""', u'sink_properties=device.description=""']' returned non-zero exit status 1

**Comment by masmu** [comment]
Your device does not identifies itself with a name. That is a problem when creating a null sink. I don't know if there is no device name set, but this should be handled better.

I will fix this shortly. In the meantime you can try to set a name in BubbleUPNP. 
```Settings -> Local Renderer -> Network name```

**Comment by masmu** [comment]
This should be fixed in the the new release.

 * __0.3.2__ - (_2015-03-14_)
    - Added the Opus Encoder (new dependency: `opus-tools`) (thanks to [MobiusHorizons](https://github.com/MobiusHorizons))
    - Fixed a bug where an empty UPNP device name made the application crash
    - Added a missing dependency (`python-gobject`)
