### ISSUE TITLE
Command '[u'pactl', u'move-sink-input', '10', '1']' returned non-zero exit 

### ISSUE THREAD

**Issue by sphaero** [masmu/pulseaudio-dlna#243]
Not sure if this is relevant but getting these errors/warnings now and then on Debian Stretch (padlna from debian repo)

```
10-01 18:25:52 pulseaudio_dlna.streamserver                   INFO     URL settings: /dWRuPSJ1dWlkOmQyOTAxYjNlLTRmNjgtZTY5NC1lODcxLTIxODM4M2JkN2MzNCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3 (udn="uuid:d2901b3e-4f68-e694-e871-218383bd7c34",type="bridge")
10-01 18:25:52 pulseaudio_dlna.streamserver                   INFO     Registered stream "/dWRuPSJ1dWlkOmQyOTAxYjNlLTRmNjgtZTY5NC1lODcxLTIxODM4M2JkN2MzNCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3" (0x7fc979980690) ...
10-01 18:25:52 pulseaudio_dlna.streamserver                   INFO     Starting processes "parec --format=s16le -d kodiraspbmc_dlna.monitor | lame -b 192 -r -"
10-01 18:25:52 pulseaudio_dlna.streamserver                   INFO     Processes of /dWRuPSJ1dWlkOmQyOTAxYjNlLTRmNjgtZTY5NC1lODcxLTIxODM4M2JkN2MzNCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3 initialized ...
10-01 18:25:52 pulseaudio_dlna.streamserver                   INFO     Unregistered stream "/dWRuPSJ1dWlkOmQyOTAxYjNlLTRmNjgtZTY5NC1lODcxLTIxODM4M2JkN2MzNCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3" (0x7fc979980690) ...
10-01 18:26:32 pulseaudio_dlna.streamserver                   INFO     Unregistered stream "/dWRuPSJ1dWlkOmQyOTAxYjNlLTRmNjgtZTY5NC1lODcxLTIxODM4M2JkN2MzNCIsdHlwZT0iYnJpZGdlIg%3D%3D/stream.mp3" (0x7fc979970e90) ...
10-01 18:26:34 pulseaudio_dlna.streamserver                   INFO     No more stream from device "Kodi (raspbmc)".
Failure: Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 551, in _on_new_message
    getattr(self, message_type)(**message)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 631, in on_bridge_disconnected
    self.switch_back(stopped_bridge, reason)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 599, in switch_back
    bridge.sink.switch_streams_to_fallback_source()
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 379, in switch_streams_to_fallback_source
    stream.switch_to_source(self.fallback_sink.index)
  File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 449, in switch_to_source
    subprocess.check_output(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'pactl', u'move-sink-input', '10', '1']' returned non-zero exit status 1
```

**Comment by masmu** [comment]
Is this still relevant?
