### ISSUE TITLE
Attribute Error on network.py

### ISSUE THREAD

**Issue by camlafit** [masmu/pulseaudio-dlna#322]
HI

From debian package 0.5.3+git20170406-1

I get this error : 
```
Jul 26 09:44:44 laptop pulseaudio-dlna.desktop[738]: 07-26 09:44:44 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink1"
Jul 26 09:44:44 laptop pulseaudio-dlna.desktop[738]: 07-26 09:44:44 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink1"
Jul 26 09:44:44 laptop pulseaudio-dlna.desktop[738]: 07-26 09:44:44 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink1"
Jul 26 09:44:44 laptop pulseaudio-dlna.desktop[738]: 07-26 09:44:44 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink1"
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]: 07-26 09:44:45 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink1
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]: 07-26 09:44:45 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Corridoio - Sonos PLAY:3 Media Renderer (DLNA)" to play ...
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]: Traceback (most recent call last):
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 693, in _handle_sink_update
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     result = future.result()
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     return self.__get_result()
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     result = self.fn(*self.args, **self.kwargs)
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/pulseaudio.py", line 738, in __handle_sink_update
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     artist=artist, title=title, thumb=thumb)
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/upnp/renderer.py", line 462, in play
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     stream_url = url or self.get_stream_url()
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/renderer.py", line 411, in get_stream_url
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     return self._encode_settings(settings, 'stream.' + self.codec.suffix)
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/plugins/renderer.py", line 390, in _encode_settings
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     server_ip = pulseaudio_dlna.utils.network.get_host_by_ip(self.ip)
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/utils/network.py", line 52, in get_host_by_ip
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     return __pyroute2_get_host_by_ip(ip)
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:   File "/usr/lib/python2.7/dist-packages/pulseaudio_dlna/utils/network.py", line 75, in __pyroute2_get_host_by_ip
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]:     if attr.cell[0] == 'RTA_PREFSRC':
Jul 26 09:44:45 laptop pulseaudio-dlna.desktop[738]: AttributeError: 'list' object has no attribute 'cell'
```

**Comment by masmu** [comment]
@camlafit : Could you please current master and check if that solves your problem?

**Comment by muammar** [comment]
@camlafit if that is the case, let us know and I can update the debian package.

**Comment by camlafit** [comment]
Hi

Are they deb master download ? I don't found it.

**Comment by muammar** [comment]
>Are they deb master download ? I don't found it.

I decided to mostly upload stable versions. But from time to time I upload `master` snapshots. You should actually clone the repo and test what @masmu asked you. I will update the debian package this weekend with latest `master` snapshot just in case.

**Comment by camlafit** [comment]
Hi

I try to compile by hand deb but I can't. python-futures is required but I don't found it in jessie packages.

**Comment by muammar** [comment]
@camlafit it seems to be available when you active the backports. [See the package here](https://packages.debian.org/jessie-backports/python-future).

**Comment by camlafit** [comment]
Hi

I do a workaround with [fpm packager](https://github.com/jordansissel/fpm/) , I've just try with master and looks ok.

This package is not provided in stable release (stretch). Looks replaced by https://packages.debian.org/stretch/python-concurrent.futures

You can update deb package from master :)

**Comment by muammar** [comment]
@camlafit thanks for confirming this. I will update the package this weekend.

**Comment by camlafit** [comment]
I've done a mistake , I use stretch and not jessie .... (I've forgotten that on my previous message, upgrade too recently :)

About fpm I do as this 
> pm -s python -t deb --no-python-fix-name --no-python-dependencies setup.py

**Comment by camlafit** [comment]
@muammar  thank for your help

**Comment by bp-dev** [comment]
@muammar I'm seeing the same issue after upgrading to 0.5.3+git20170406-1 which seems to be the most recent version available. 
Did you got around to update the debian package? Or it ended up being more complicated?
Thanks!
