### ISSUE TITLE
unicode error on Ubuntu 16.04 after python upgraded to Python 2.7.12

### ISSUE THREAD

**Issue by trappedinspacetime** [masmu/pulseaudio-dlna#334]
First of all, thanks a lot for useful project.
A few days ago after usual `apt upgrage` python version upgraded, subsequently `pulseaudio-dlna` failed with the following eerror:

      Exception in thread Thread-3:
      Traceback (most recent call last):
        File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
        File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
        File "/usr/local/lib/python2.7/dist-packages/pulseaudio_dlna-0.5.2-py2.7.egg/pulseaudio_dlna/plugins/dlna/__init__.py", line 55, in launch_discover
    discover.search(ssdp_ttl=ttl)
        File "/usr/local/lib/python2.7/dist-packages/pulseaudio_dlna-0.5.2-py2.7.egg/pulseaudio_dlna/plugins/dlna/ssdp/discover.py", line 68, in search
    self._search(self.host or '', ssdp_ttl, ssdp_mx, ssdp_amount)
        File "/usr/local/lib/python2.7/dist-packages/pulseaudio_dlna-0.5.2-py2.7.egg/pulseaudio_dlna/plugins/dlna/ssdp/discover.py", line 110, in _search
    header = header.decode(guess['encoding'])
        File "/usr/lib/python2.7/encodings/iso8859_7.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
      UnicodeDecodeError: 'charmap' codec can't decode byte 0xff in position 543: character maps to <undefined>

**Comment by trappedinspacetime** [comment]
adding the below lines  to top of `/usr/lib/python2.7/sitecustomize.py` fixed the error.

       import sys
       sys.setdefaultencoding('UTF8')
