### ISSUE TITLE
Ubuntu 18.04 Pulseaudio-dlna does not see ChromeCast

### ISSUE THREAD

**Issue by kyleamadio** [masmu/pulseaudio-dlna#350]
Pulseaudio-dlna sees other dlna enabled devices however it cannot see the Chromecast. Chrome browser sees it fine. Tried opening various ports in the firewall - did not help.

**Comment by minsonj2016** [comment]
I installed 18.04 in a Virtualbox VM and it worked for me . (played to chromecast audio devices)

**Comment by kyleamadio** [comment]
Great - what are you firewall settings and version numbers - 

kylea@kylea-XPS-15-9570:~$ pulseaudio-dlna
07-30 17:45:24 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
07-30 17:45:24 pulseaudio_dlna.application                    INFO     Binding to *:8080
07-30 17:45:24 pulseaudio_dlna.application                    INFO     Encoder settings:
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
07-30 17:45:24 pulseaudio_dlna.application                    INFO     Codec settings:
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="1" mime_type="audio/L16" backend="generic">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
07-30 17:45:24 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/kylea/.local/lib/python2.7/site-packages/zeroconf.py", line 1133, in run
    reader.handle_read(socket_)
  File "/home/kylea/.local/lib/python2.7/site-packages/zeroconf.py", line 1175, in handle_read
    msg = DNSIncoming(data)
  File "/home/kylea/.local/lib/python2.7/site-packages/zeroconf.py", line 644, in __init__
    self.read_questions()
  File "/home/kylea/.local/lib/python2.7/site-packages/zeroconf.py", line 667, in read_questions
    name = self.read_name()
  File "/home/kylea/.local/lib/python2.7/site-packages/zeroconf.py", line 756, in read_name
    t = length & 0xC0
TypeError: unsupported operand type(s) for &: 'str' and 'int'

07-30 17:45:29 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()

**Comment by minsonj2016** [comment]
you seem to be getting a python error above .
here is what I get

test@test-VirtualBox:~$ pulseaudio-dlna
07-30 09:00:11 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
07-30 09:00:11 pulseaudio_dlna.application                    INFO     Binding to *:8080
07-30 09:00:11 pulseaudio_dlna.application                    INFO     Encoder settings:
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="False">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="False" sample-rate="44100" channels="2">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="False">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
07-30 09:00:11 pulseaudio_dlna.application                    INFO     Codec settings:
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac" backend="generic">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="1" mime_type="audio/L16" backend="generic">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus" backend="generic">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3" backend="generic">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac" backend="generic">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav" backend="generic">
07-30 09:00:11 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg" backend="generic">
07-30 09:00:11 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Porch (Chromecast)".
07-30 09:00:12 pulseaudio_dlna.pulseaudio                     INFO     Added the device "DenPorch (Chromecast)".
07-30 09:00:12 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Den (Chromecast)".
07-30 09:00:21 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()

**Comment by minsonj2016** [comment]
here are the python packages I have installed

libpython-stdlib/bionic,now 2.7.15~rc1-1 amd64 [installed,automatic]
libpython2.7/bionic,now 2.7.15~rc1-1 amd64 [installed]
libpython2.7-minimal/bionic,now 2.7.15~rc1-1 amd64 [installed]
libpython2.7-stdlib/bionic,now 2.7.15~rc1-1 amd64 [installed]
libpython3-stdlib/bionic-updates,now 3.6.5-3ubuntu1 amd64 [installed]
libpython3.6/bionic,now 3.6.5-3 amd64 [installed]
libpython3.6-minimal/bionic,now 3.6.5-3 amd64 [installed]
libpython3.6-stdlib/bionic,now 3.6.5-3 amd64 [installed]
python/bionic,now 2.7.15~rc1-1 amd64 [installed,automatic]
python-apt-common/now 1.6.1 all [installed,upgradable to: 1.6.2]
python-asn1crypto/bionic,bionic,now 0.24.0-1 all [installed,automatic]
python-bs4/bionic,bionic,now 4.6.0-1 all [installed,automatic]
python-certifi/bionic,bionic,now 2018.1.18-2 all [installed,automatic]
python-cffi-backend/bionic,now 1.11.5-1 amd64 [installed,automatic]
python-chardet/bionic,bionic,now 3.0.4-1 all [installed,automatic]
python-concurrent.futures/bionic,bionic,now 3.2.0-1 all [installed,automatic]
python-cryptography/bionic-updates,bionic-security,now 2.1.4-1ubuntu1.2 amd64 [installed,automatic]
python-dbus/bionic,now 1.2.6-1 amd64 [installed,automatic]
python-docopt/bionic,bionic,now 0.6.2-1build1 all [installed,automatic]
python-enum34/bionic,bionic,now 1.1.6-2 all [installed,automatic]
python-gi/bionic,now 3.26.1-2 amd64 [installed,automatic]
python-html5lib/bionic,bionic,now 0.999999999-1 all [installed,automatic]
python-idna/bionic,bionic,now 2.6-1 all [installed,automatic]
python-ipaddress/bionic,bionic,now 1.0.17-1 all [installed,automatic]
python-lxml/bionic,now 4.2.1-1 amd64 [installed,automatic]
python-minimal/bionic,now 2.7.15~rc1-1 amd64 [installed,automatic]
python-netifaces/bionic,now 0.10.4-0.1build4 amd64 [installed,automatic]
python-notify2/bionic,bionic,now 0.3-3 all [installed,automatic]
python-openssl/bionic,bionic,now 17.5.0-1ubuntu1 all [installed,automatic]
python-pkg-resources/bionic,bionic,now 39.0.1-2 all [installed,automatic]
python-protobuf/bionic,now 3.0.0-9.1ubuntu1 amd64 [installed,automatic]
python-psutil/bionic,now 5.4.2-1 amd64 [installed,automatic]
python-pyroute2/bionic,bionic,now 0.4.21-0.1ubuntu2 all [installed,automatic]
python-requests/bionic,bionic,now 2.18.4-2 all [installed,automatic]
python-setproctitle/bionic,now 1.1.10-1build2 amd64 [installed,automatic]
python-setuptools/bionic,bionic,now 39.0.1-2 all [installed,automatic]
python-six/bionic,bionic,now 1.11.0-2 all [installed,automatic]
python-talloc/bionic,now 2.1.10-2ubuntu1 amd64 [installed]
python-urllib3/bionic,bionic,now 1.22-1 all [installed,automatic]
python-webencodings/bionic,bionic,now 0.5-2 all [installed,automatic]
python-zeroconf/bionic,bionic,now 0.19.1-1 all [installed,automatic]
python2.7/bionic,now 2.7.15~rc1-1 amd64 [installed,automatic]
python2.7-minimal/bionic,now 2.7.15~rc1-1 amd64 [installed,automatic]
python3/bionic-updates,now 3.6.5-3ubuntu1 amd64 [installed]
python3-apport/bionic-updates,bionic-updates,now 2.20.9-0ubuntu7.2 all [installed]
python3-apt/now 1.6.1 amd64 [installed,upgradable to: 1.6.2]
python3-aptdaemon/bionic,bionic,now 1.1.1+bzr982-0ubuntu19 all [installed]
python3-aptdaemon.gtk3widgets/bionic,bionic,now 1.1.1+bzr982-0ubuntu19 all [installed]
python3-asn1crypto/bionic,bionic,now 0.24.0-1 all [installed]
python3-brlapi/bionic,now 5.5-4ubuntu2 amd64 [installed]
python3-cairo/bionic,now 1.16.2-1 amd64 [installed]
python3-certifi/bionic,bionic,now 2018.1.18-2 all [installed]
python3-cffi-backend/bionic,now 1.11.5-1 amd64 [installed]
python3-chardet/bionic,bionic,now 3.0.4-1 all [installed]
python3-commandnotfound/bionic-updates,bionic-updates,now 18.04.5 all [installed]
python3-crypto/bionic,now 2.6.1-8ubuntu2 amd64 [installed]
python3-cryptography/bionic,now 2.1.4-1ubuntu1.1 amd64 [installed,upgradable to: 2.1.4-1ubuntu1.2]
python3-cups/bionic,now 1.9.73-2 amd64 [installed]
python3-cupshelpers/bionic,bionic,now 1.5.11-1ubuntu2 all [installed]
python3-dbus/bionic,now 1.2.6-1 amd64 [installed]
python3-debconf/bionic,bionic,now 1.5.66 all [installed]
python3-debian/bionic,bionic,now 0.1.32 all [installed]
python3-defer/bionic,bionic,now 1.0.6-2build1 all [installed]
python3-distro-info/bionic,bionic,now 0.18 all [installed]
python3-distupgrade/now 1:18.04.19 all [installed,upgradable to: 1:18.04.21]
python3-gdbm/bionic,now 3.6.5-3 amd64 [installed]
python3-gi/bionic,now 3.26.1-2 amd64 [installed]
python3-gi-cairo/bionic,now 3.26.1-2 amd64 [installed]
python3-httplib2/bionic,bionic,now 0.9.2+dfsg-1 all [installed]
python3-idna/bionic,bionic,now 2.6-1 all [installed]
python3-keyring/bionic,bionic,now 10.6.0-1 all [installed]
python3-keyrings.alt/bionic,bionic,now 3.0-1 all [installed]
python3-launchpadlib/bionic,bionic,now 1.10.6-1 all [installed]
python3-lazr.restfulclient/bionic,bionic,now 0.13.5-1 all [installed]
python3-lazr.uri/bionic,bionic,now 1.0.3-2build1 all [installed]
python3-louis/bionic-updates,bionic-updates,bionic-security,bionic-security,now 3.5.0-1ubuntu0.2 all [installed]
python3-macaroonbakery/bionic,bionic,now 1.1.3-1 all [installed]
python3-mako/bionic,bionic,now 1.0.7+ds1-1 all [installed]
python3-markupsafe/bionic,now 1.0-1build1 amd64 [installed]
python3-minimal/bionic-updates,now 3.6.5-3ubuntu1 amd64 [installed]
python3-nacl/bionic,now 1.1.2-1build1 amd64 [installed]
python3-oauth/bionic,bionic,now 1.0.1-5 all [installed]
python3-olefile/bionic,bionic,now 0.45.1-1 all [installed]
python3-pexpect/bionic,bionic,now 4.2.1-1 all [installed]
python3-pil/bionic,now 5.1.0-1 amd64 [installed]
python3-pkg-resources/bionic,bionic,now 39.0.1-2 all [installed]
python3-problem-report/bionic-updates,bionic-updates,now 2.20.9-0ubuntu7.2 all [installed]
python3-protobuf/bionic,now 3.0.0-9.1ubuntu1 amd64 [installed]
python3-ptyprocess/bionic,bionic,now 0.5.2-1 all [installed]
python3-pyatspi/bionic,bionic,now 2.26.0+dfsg-1 all [installed]
python3-pymacaroons/bionic,bionic,now 0.13.0-1 all [installed]
python3-renderpm/bionic,now 3.4.0-3build1 amd64 [installed]
python3-reportlab/bionic,bionic,now 3.4.0-3build1 all [installed]
python3-reportlab-accel/bionic,now 3.4.0-3build1 amd64 [installed]
python3-requests/bionic,bionic,now 2.18.4-2 all [installed]
python3-requests-unixsocket/bionic,bionic,now 0.1.5-3 all [installed]
python3-rfc3339/bionic,bionic,now 1.0-4 all [installed]
python3-secretstorage/bionic,bionic,now 2.3.1-2 all [installed]
python3-simplejson/bionic,now 3.13.2-1 amd64 [installed]
python3-six/bionic,bionic,now 1.11.0-2 all [installed]
python3-software-properties/now 0.96.24.32.3 all [installed,upgradable to: 0.96.24.32.4]
python3-speechd/bionic,bionic,now 0.8.8-1ubuntu1 all [installed]
python3-systemd/bionic,now 234-1build1 amd64 [installed]
python3-tz/bionic,bionic,now 2018.3-2 all [installed]
python3-uno/bionic,now 1:6.0.3-0ubuntu1 amd64 [installed]
python3-update-manager/now 1:18.04.11.3 all [installed,upgradable to: 1:18.04.11.4]
python3-urllib3/bionic,bionic,now 1.22-1 all [installed]
python3-wadllib/bionic,bionic,now 1.3.2-3 all [installed]
python3-xdg/bionic,bionic,now 0.25-4ubuntu1 all [installed]
python3-xkit/bionic,bionic,now 0.5.0ubuntu2 all [installed]
python3-yaml/bionic,now 3.12-1build2 amd64 [installed]
python3-zope.interface/bionic,now 4.3.2-1build2 amd64 [installed]
python3.6/bionic,now 3.6.5-3 amd64 [installed]
python3.6-minimal/bionic,now 3.6.5-3 amd64 [installed]

**Comment by kyleamadio** [comment]
Thanks - checked all them - all presented and accounted for

**Comment by minsonj2016** [comment]
you are positive you have
python2-enum 
python3-zeroconf.noarch
python2-enum34

installed ?

**Comment by xezpeleta** [comment]
Same Python error here with Ubuntu 18.04.

I've installed pulseaudio-dlna from the official Ubuntu universe repo (apt install pulseaudio-dlna)

```
Exception in thread zeroconf-Engine:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1133, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 1175, in handle_read
    msg = DNSIncoming(data)
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 644, in __init__
    self.read_questions()
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 667, in read_questions
    name = self.read_name()
  File "/usr/local/lib/python2.7/dist-packages/zeroconf.py", line 756, in read_name
    t = length & 0xC0
TypeError: unsupported operand type(s) for &: 'str' and 'int'
```
