### ISSUE TITLE
stream_server segfaulting

### ISSUE THREAD

**Issue by chainria** [masmu/pulseaudio-dlna#396]
Hello,

I wanted to try pulseaudio-dlna on gentoo, installed the 0.6.0 version by ebuilds (python3@b0db8137224f5a293329a60187365168304c3768). I tried two media renderers but none seemed to work. After poking around in the code I found out which threads needed to be there, but I never even saw any stream_server thread. After poking around some more, I found the culprit:

[643360.248245] traps: stream_server[26045] general protection ip:7f9ed5378020 sp:7ffbbcb65fc0 error:0 in libffi.so.7.1.0[7f9ed5374000+6000]
[643443.360732] traps: stream_server[26082] general protection ip:7f21dad42020 sp:7ffa18acab20 error:0 in libffi.so.7.1.0[7f21dad3e000+6000]
[643842.092474] stream_server[26308]: segfault at 200000000 ip 00007f283bcbf020 sp 00007ffdc7ab4b50 error 4 in libffi.so.7.1.0[7f283bcbb000+6000]
[643842.092482] Code: af 01 00 00 48 8b 45 90 4c 8b 60 08 31 db 4c 8d 2d 41 23 00 00 31 c0 48 89 45 c8 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 <49> 8b 3c dc 48 8d 75 a0 31 d2 e8 f1 01 00 00 48 85 c0 0f 84 88 00
[644396.043655] traps: stream_server[26539] general protection ip:7fb69d82d020 sp:7ffb7acf39f0 error:0 in libffi.so.7.1.0[7fb69d829000+6000]
[644426.616840] stream_server[26592]: segfault at 417200000041 ip 00007f68b0fb2020 sp 00007ff8ce7df350 error 4 in libffi.so.7.1.0[7f68b0fae000+6000]
[644426.616848] Code: af 01 00 00 48 8b 45 90 4c 8b 60 08 31 db 4c 8d 2d 41 23 00 00 31 c0 48 89 45 c8 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 <49> 8b 3c dc 48 8d 75 a0 31 d2 e8 f1 01 00 00 48 85 c0 0f 84 88 00
[644623.982431] stream_server[26827]: segfault at 417200000041 ip 00007f38d1d14020 sp 00007ffba9d820d0 error 4 in libffi.so.7.1.0[7f38d1d10000+6000]
[644623.982443] Code: af 01 00 00 48 8b 45 90 4c 8b 60 08 31 db 4c 8d 2d 41 23 00 00 31 c0 48 89 45 c8 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 <49> 8b 3c dc 48 8d 75 a0 31 d2 e8 f1 01 00 00 48 85 c0 0f 84 88 00
[644818.818247] traps: ssdp_listener[26935] general protection ip:7ffafd5d8020 sp:7ff9776c1d50 error:0 in libffi.so.7.1.0[7ffafd5d4000+6000]
[644838.300356] stream_server[26952]: segfault at 26373 ip 00007fd2b3470020 sp 00007ff9133a15c0 error 4 in libffi.so.7.1.0[7fd2b346c000+6000]
[644838.300366] Code: af 01 00 00 48 8b 45 90 4c 8b 60 08 31 db 4c 8d 2d 41 23 00 00 31 c0 48 89 45 c8 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 <49> 8b 3c dc 48 8d 75 a0 31 d2 e8 f1 01 00 00 48 85 c0 0f 84 88 00
[645080.888241] traps: stream_server[27091] general protection ip:7fb62916a020 sp:7ffaa5b0b3c0 error:0 in libffi.so.7.1.0[7fb629166000+6000]
[645152.677388] traps: stream_server[27158] general protection ip:7fbcb0683020 sp:7ffec6c713f0 error:0 in libffi.so.7.1.0[7fbcb067f000+6000]
[645173.324885] traps: ssdp_listener[27205] general protection ip:7f1f8e197020 sp:7f1f32366580 error:0 in libffi.so.7.1.0[7f1f8e193000+6000]
[645322.759547] traps: ssdp_listener[27276] general protection ip:7f1a4c15b020 sp:7f19f4275580 error:0 in libffi.so.7.1.0[7f1a4c157000+6000]
[645330.550003] traps: stream_server[27299] general protection ip:7feb4fa36020 sp:7ffc388241c0 error:0 in libffi.so.7.1.0[7feb4fa32000+6000]
[645396.105306] traps: stream_server[27357] general protection ip:7f9dbf898020 sp:7ffcd48224e0 error:0 in libffi.so.7.1.0[7f9dbf894000+6000]
[645695.970239] traps: stream_server[27494] general protection ip:7f60886e2020 sp:7ff902822a10 error:0 in libffi.so.7.1.0[7f60886de000+6000]
[646070.075837] traps: stream_server[27622] general protection ip:7ff5fc8ac020 sp:7ff938f578f0 error:0 in libffi.so.7.1.0[7ff5fc8a8000+6000]
[646125.570348] traps: stream_server[27659] general protection ip:7ff05b0d9020 sp:7ff89f6639b0 error:0 in libffi.so.7.1.0[7ff05b0d5000+6000]
[646390.537581] traps: stream_server[27859] general protection ip:7fde472b4020 sp:7ffb47efdf30 error:0 in libffi.so.7.1.0[7fde472b0000+6000]
[646516.346032] traps: stream_server[27952] general protection ip:7ffff646b020 sp:7ffcc454a090 error:0 in libffi.so.7.1.0[7ffff6467000+6000]
[646591.374339] traps: stream_server[28009] general protection ip:7ffff646b020 sp:7ffe8c841a50 error:0 in libffi.so.7.1.0[7ffff6467000+6000]

If there is anything I can do to help, just tell me what I need to do and I will give it a try!

--- System info follows ---

chain@richIx220 ~ $ emerge --info
Portage 2.3.89 (python 3.6.10-final-0, default/linux/amd64/17.0/desktop/plasma, gcc-9.2.0, glibc-2.29-r7, 4.19.72-gentoo-richBOOK x86_64)
=================================================================
System uname: Linux-4.19.72-gentoo-richBOOK-x86_64-Intel-R-_Core-TM-_i5-2520M_CPU_@_2.50GHz-with-gentoo-2.6
KiB Mem:     7993404 total,    479060 free
KiB Swap:    8388604 total,   5760252 free
Timestamp of repository gentoo: Wed, 01 Apr 2020 19:37:25 +0000
Head commit of repository gentoo: 174605aea4f7bb0f89f17ef0e3169922083ef036

Head commit of repository chain: 0191e4d5a99197fc2d38bf24b9c4d0e8dda3f279

Timestamp of repository dotnet: Tue, 31 Mar 2020 16:40:41 +0000
Head commit of repository dotnet: eb90031b5890674a357deda256566594122eaab2

sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.33.1 p2) 2.33.1
app-shells/bash:          4.4_p23-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.30.1::gentoo
dev-lang/python:          2.7.17-r1::gentoo, 3.6.10::gentoo
dev-util/cmake:           3.16.5::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/openrc:          0.42.1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.13.4-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.33.1-r1::gentoo
sys-devel/gcc:            9.2.0-r2::gentoo
sys-devel/gcc-config:     2.2.1::gentoo
sys-devel/libtool:        2.4.6-r6::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 5.4::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r7::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo.git
    priority: -1000

chain
    location: /usr/local/portage
    sync-type: git
    sync-uri: https://chain@git.rpgfiction.net/portage-overlay.git
    masters: gentoo

dotnet
    location: /var/db/repos/dotnet
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/dotnet.git
    masters: gentoo

crossdev
    location: /usr/local/portage-crossdev
    masters: gentoo
    priority: 10

tlp
    location: /var/lib/layman/tlp
    masters: gentoo
    priority: 50

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="@FREE"
CBUILD="x86_64-pc-linux-gnu"
CC="clang"
CFLAGS="-march=native -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXX="clang++"
CXXFLAGS="-march=native -O2 -pipe"
DISTDIR="/usr/portage/distfiles"
EMERGE_DEFAULT_OPTS="--quiet-build=y"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs candy config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://distfiles.gentoo.org"
LANG="de_AT.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LINGUAS="de"
MAKEOPTS="-j4"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/tmp"
USE="X a52 aac acl acpi activities alsa amd64 berkdb bluetooth bluray bzip2 cairo cdda cdr clang cli crypt cups dbus declarative dri dts dvd dvdr elogind emboss encode exif flac fortran gdbm gif gpm iconv icu ipv6 jpeg kde kipi kwallet lcms libnotify libtirpc mad minimal mng mp3 mp4 mpeg multilib ncurses netboot networkmanager nls nocd nptl ogg opengl openmp pam pango pcre pdf phonon plasma png policykit ppds pulseaudio qml qt5 readline sdl seccomp smp split-usr sse3 ssl ssse3 startup-notification svg tcpd threads tiff truetype udev udisks unicode upower usb vaapi vdpau vorbis wayland widgets wifi wxwidgets x264 xattr xcb xcomposite xinerama xml xv xvid xvmc zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev synaptics void wacom" KERNEL="linux" L10N="de" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python3_6" QEMU_SOFTMMU_TARGETS="arm i386 x86_64" QEMU_USER_TARGETS="arm i386 x86_64" RUBY_TARGETS="ruby24 ruby25" USERLAND="GNU" VIDEO_CARDS="fbdev intel i965 modesetting" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CPPFLAGS, CTARGET, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS

**Comment by chainria** [comment]
I was able to generate a core file, but I am pretty sure the back trace won't be of much help I am afraid.

#0  0x00007f78afec3964 in  () at /usr/lib64/libffi.so.7
#1  0x00007f78afec3d80 in  () at /usr/lib64/libffi.so.7
#2  0x00007f78af8b48f9 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#3  0x00007f78af8b4c62 in  () at /usr/lib64/libglib-2.0.so.0
#4  0x00007f78af8b4f6f in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#5  0x00007f78afec3bed in  () at /usr/lib64/libffi.so.7
#6  0x00007f78afec317c in  () at /usr/lib64/libffi.so.7
#7  0x00007f78af9ef258 in  () at /usr/lib64/python3.6/site-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
#8  0x00007f78af9f0123 in  () at /usr/lib64/python3.6/site-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
#9  0x00007f78af9e4085 in  () at /usr/lib64/python3.6/site-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
#10 0x00007f78b1773210 in _PyObject_FastCallDict () at /usr/lib64/libpython3.6m.so.1.0
#11 0x00007f78b1832852 in  () at /usr/lib64/libpython3.6m.so.1.0
#12 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#13 0x00007f78b18331a6 in  () at /usr/lib64/libpython3.6m.so.1.0
#14 0x00007f78b1833acf in  () at /usr/lib64/libpython3.6m.so.1.0
#15 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#16 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#17 0x00007f78b18331a6 in  () at /usr/lib64/libpython3.6m.so.1.0
#18 0x00007f78b1833acf in  () at /usr/lib64/libpython3.6m.so.1.0
#19 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#20 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#21 0x00007f78b1834007 in _PyFunction_FastCallDict () at /usr/lib64/libpython3.6m.so.1.0
#22 0x00007f78b1773180 in _PyObject_FastCallDict () at /usr/lib64/libpython3.6m.so.1.0
#23 0x00007f78b17732f3 in _PyObject_Call_Prepend () at /usr/lib64/libpython3.6m.so.1.0
#24 0x00007f78b1772fd2 in PyObject_Call () at /usr/lib64/libpython3.6m.so.1.0
#25 0x00007f78b1830107 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#26 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#27 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#28 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#29 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#30 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#31 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#32 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#33 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#34 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#35 0x00007f78b1834007 in _PyFunction_FastCallDict () at /usr/lib64/libpython3.6m.so.1.0
#36 0x00007f78b1773180 in _PyObject_FastCallDict () at /usr/lib64/libpython3.6m.so.1.0
#37 0x00007f78b17732f3 in _PyObject_Call_Prepend () at /usr/lib64/libpython3.6m.so.1.0
#38 0x00007f78b1772fd2 in PyObject_Call () at /usr/lib64/libpython3.6m.so.1.0
#39 0x00007f78b17d2dda in  () at /usr/lib64/libpython3.6m.so.1.0
#40 0x00007f78b17cf481 in  () at /usr/lib64/libpython3.6m.so.1.0
#41 0x00007f78b1773210 in _PyObject_FastCallDict () at /usr/lib64/libpython3.6m.so.1.0
#42 0x00007f78b1832852 in  () at /usr/lib64/libpython3.6m.so.1.0
#43 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#44 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#45 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#46 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#47 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#48 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#49 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#50 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#51 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#52 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#53 0x00007f78b18331a6 in  () at /usr/lib64/libpython3.6m.so.1.0
#54 0x00007f78b1833acf in  () at /usr/lib64/libpython3.6m.so.1.0
#55 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#56 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#57 0x00007f78b1833b73 in  () at /usr/lib64/libpython3.6m.so.1.0
#58 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#59 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#60 0x00007f78b1833c23 in  () at /usr/lib64/libpython3.6m.so.1.0
#61 0x00007f78b1832859 in  () at /usr/lib64/libpython3.6m.so.1.0
#62 0x00007f78b182fec7 in _PyEval_EvalFrameDefault () at /usr/lib64/libpython3.6m.so.1.0
#63 0x00007f78b18331a6 in  () at /usr/lib64/libpython3.6m.so.1.0
#64 0x00007f78b182a214 in PyEval_EvalCode () at /usr/lib64/libpython3.6m.so.1.0
#65 0x00007f78b185b33f in PyRun_FileExFlags () at /usr/lib64/libpython3.6m.so.1.0
#66 0x00007f78b185a999 in PyRun_SimpleFileExFlags () at /usr/lib64/libpython3.6m.so.1.0
#67 0x00007f78b1874599 in Py_Main () at /usr/lib64/libpython3.6m.so.1.0
#68 0x000000000040129c in main ()
