### ISSUE TITLE
no sound with python 3 , latest python3 branch

### ISSUE THREAD

**Issue by JPGuillemin** [masmu/pulseaudio-dlna#397]
`pulseaudio_dlna.application                    INFO     Using version: 0.6.0
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Binding to 192.168.1.124:2869
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Loaded device config "/home/hyperion/.local/share/pulseaudio-dlna/devices.json"
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Encoder settings:
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Codec settings:
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AacCodec enabled="False" priority="0" mime_type="audio/aac" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="False" priority="0" mime_type="audio/flac" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <L16Codec enabled="False" priority="0" mime_type="audio/L16" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="False" priority="0" mime_type="audio/mp3" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OggCodec enabled="False" priority="0" mime_type="audio/ogg" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="False" priority="0" mime_type="audio/opus" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="24" mime_type="audio/wav" backend="generic">
04-09 08:53:37 pulseaudio_dlna.plugins.chromecast             INFO     ChromecastPlugin.discover()
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Module "module-dbus-protocol" (id=22) loaded.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for $PULSE_DBUS_SERVER unsuccessful.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for /run/pulse/dbus-socket unsuccessful.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for $XDG_RUNTIME_DIR unsuccessful.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for org.PulseAudio.ServerLookup1 successful (unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket).
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Found the following pulseaudio server addresses: unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Connecting to pulseaudio on "unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "TRITON (Chromecast)" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "PHOBOS (Chromecast)" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "THALASSA (Chromecast)" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "MARS (Chromecast)" ...
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/gi/overrides/GLib.py", line 671, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 641, in _on_new_message
    getattr(self, message_type)(**message)
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 835, in add_device
    sink = self.create_null_sink(
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 271, in create_null_sink
    if int(sink.module.index) == module_id:
ValueError: invalid literal for int() with base 10: 'dbus.UInt32(23, variant_level=1)'
`

**Comment by JPGuillemin** [comment]
> pulseaudio_dlna.application                    INFO     Using version: 0.6.0
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Binding to 192.168.1.124:2869
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Loaded device config "/home/hyperion/.local/share/pulseaudio-dlna/devices.json"
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Encoder settings:
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
04-09 08:53:37 pulseaudio_dlna.application                    INFO     Codec settings:
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <AacCodec enabled="False" priority="0" mime_type="audio/aac" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="False" priority="0" mime_type="audio/flac" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <L16Codec enabled="False" priority="0" mime_type="audio/L16" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="False" priority="0" mime_type="audio/mp3" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OggCodec enabled="False" priority="0" mime_type="audio/ogg" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="False" priority="0" mime_type="audio/opus" backend="generic">
04-09 08:53:37 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="24" mime_type="audio/wav" backend="generic">
04-09 08:53:37 pulseaudio_dlna.plugins.chromecast             INFO     ChromecastPlugin.discover()
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Module "module-dbus-protocol" (id=22) loaded.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for $PULSE_DBUS_SERVER unsuccessful.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for /run/pulse/dbus-socket unsuccessful.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for $XDG_RUNTIME_DIR unsuccessful.
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Probing for org.PulseAudio.ServerLookup1 successful (unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket).
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Found the following pulseaudio server addresses: unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket
04-09 08:53:37 pulseaudio_dlna.pulseaudio                     INFO     Connecting to pulseaudio on "unix:path=/tmp/pulse-PKdhtXMmr18n/dbus-socket" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "TRITON (Chromecast)" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "PHOBOS (Chromecast)" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "THALASSA (Chromecast)" ...
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pychromecast                                   INFO     Querying device status
04-09 08:53:37 pulseaudio_dlna.holder                         INFO     Skipped the device "MARS (Chromecast)" ...
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/gi/overrides/GLib.py", line 671, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 641, in _on_new_message
    getattr(self, message_type)(**message)
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 835, in add_device
    sink = self.create_null_sink(
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 271, in create_null_sink
    if int(sink.module.index) == module_id:
ValueError: invalid literal for int() with base 10: 'dbus.UInt32(23, variant_level=1)'

**Comment by JPGuillemin** [comment]
> ndle_sink_update /org/pulseaudio/core1/sink1
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 773, in _handle_sink_update
    result = future.result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib64/python3.8/site-packages/pulseaudio_dlna/pulseaudio.py", line 810, in __handle_sink_update
    if bridge.sink.object_path == sink_path:
AttributeError: 'NoneType' object has no attribute 'object_path'

**Comment by minsonj2016** [comment]
I have the same issue (maybe) . This on Kubuntu 18.04 . This debug is from trying to play to a chromecast audio . It (pa_dlna) finds all my devices . When I try to play a song I can hear the chromecast 'boing' and thats it .

4-11 06:36:03 pulseaudio_dlna.application                    INFO     Using version: 0.5.2
04-11 06:36:03 pulseaudio_dlna.application                    INFO     Binding to *:8080
04-11 06:36:03 pulseaudio_dlna.application                    INFO     Encoder settings:
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvAacEncoder available="False" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvFlacEncoder available="False">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvL16Encoder available="False" sample-rate="44100" channels="2">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvMp3Encoder available="False" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvOggEncoder available="False" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvOpusEncoder available="False" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AVConvWavEncoder available="False">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegAacEncoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegFlacEncoder available="True">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegL16Encoder available="True" sample-rate="44100" channels="2">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegMp3Encoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegOggEncoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegOpusEncoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FFMpegWavEncoder available="True">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FaacAacEncoder available="False" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FlacFlacEncoder available="True">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <LameMp3Encoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <OggencOggEncoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <OpusencOpusEncoder available="True" bit-rate="192">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <SoxL16Encoder available="True" sample-rate="44100" channels="2">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <SoxWavEncoder available="True">
04-11 06:36:03 pulseaudio_dlna.application                    INFO     Codec settings:
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <AacCodec enabled="False" priority="0" mime_type="audio/aac" backend="generic">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <L16Codec enabled="False" priority="0" mime_type="audio/L16" backend="generic">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="False" priority="0" mime_type="audio/opus" backend="generic">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="False" priority="0" mime_type="audio/mp3" backend="generic">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="False" priority="0" mime_type="audio/flac" backend="generic">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="24" mime_type="audio/wav" backend="generic">
04-11 06:36:03 pulseaudio_dlna.application                    INFO       <OggCodec enabled="False" priority="0" mime_type="audio/ogg" backend="generic">
04-11 06:36:03 pulseaudio_dlna.pulseaudio                     INFO     Added the device "ccden (Chromecast)".
04-11 06:36:03 pulseaudio_dlna.pulseaudio                     INFO     Added the device "ccdenccAporch (Chromecast)".
04-11 06:36:03 pulseaudio_dlna.pulseaudio                     INFO     Added the device "ccAporch (Chromecast)".
04-11 06:36:03 pulseaudio_dlna.pulseaudio                     INFO     Added the device "ccAdenccAporch (Chromecast)".
04-11 06:36:03 pulseaudio_dlna.pulseaudio                     INFO     Added the device "ccAden (Chromecast)".
04-11 06:36:04 pulseaudio_dlna.pulseaudio                     INFO     Added the device "Den (DLNA)".
04-11 06:36:17 pulseaudio_dlna.discover                       INFO     SSDPDiscover.search()
04-11 08:46:50 pulseaudio_dlna.pulseaudio                     INFO     Updated device "ccAdenccAporch (Chromecast)" - New settings: 192.168.1.111:42292
04-11 08:47:01 pulseaudio_dlna.pulseaudio                     INFO     Updated device "ccAdenccAporch (Chromecast)" - New settings: 192.168.1.154:42292
04-11 11:15:06 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream0"
04-11 11:15:06 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream0"
04-11 11:15:06 pulseaudio_dlna.pulseaudio                     INFO     on_new_playback_stream "/org/pulseaudio/core1/playback_stream1"
04-11 11:15:06 pulseaudio_dlna.pulseaudio                     INFO     on_device_updated "/org/pulseaudio/core1/sink0"
04-11 11:15:07 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink3
04-11 11:15:07 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "ccAporch (Chromecast)" to play ...
04-11 11:15:10 pulseaudio_dlna.streamserver                   INFO     URL settings: /dHlwZT0iaW1hZ2UiLG5hbWU9ImRlZmF1bHQucG5nIg%3D%3D/ (type="image",name="default.png")
04-11 11:15:10 pulseaudio_dlna.streamserver                   INFO     URL settings: /dWRuPSJ1dWlkOmY5NmEyN2E1YWMzMTk5YjkyODBmNjJmMmRhNWJkN2Y5Iix0eXBlPSJicmlkZ2Ui/stream.wav (udn="uuid:f96a27a5ac3199b9280f62f2da5bd7f9",type="bridge")
04-11 11:15:10 pulseaudio_dlna.streamserver                   INFO     Registered stream "/dWRuPSJ1dWlkOmY5NmEyN2E1YWMzMTk5YjkyODBmNjJmMmRhNWJkN2Y5Iix0eXBlPSJicmlkZ2Ui/stream.wav" (0x7f08ff87d2d0) ...
04-11 11:15:10 pulseaudio_dlna.streamserver                   INFO     Starting processes "parec --format=s16le -d ccaporch_chromecast.monitor | sox -t raw -b 16 -e signed -c 2 -r 44100 - -t wav -b 16 -e signed -c 2 -r 44100 -L -"
04-11 11:15:10 pulseaudio_dlna.streamserver                   INFO     Processes of /dWRuPSJ1dWlkOmY5NmEyN2E1YWMzMTk5YjkyODBmNjJmMmRhNWJkN2Y5Iix0eXBlPSJicmlkZ2Ui/stream.wav initialized ...
sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it
04-11 11:15:17 pulseaudio_dlna.pulseaudio                     INFO     The device "ccAporch (Chromecast)" is playing.
04-11 11:15:17 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink3 finished!
04-11 11:15:17 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink0
04-11 11:15:17 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "ccAporch (Chromecast)" to stop ...
04-11 11:15:18 pulseaudio_dlna.pulseaudio                     INFO     The device "ccAporch (Chromecast)" was stopped.
04-11 11:15:18 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink0 finished!
04-11 11:16:35 pulseaudio_dlna.pulseaudio                     INFO     on_playback_stream_removed "/org/pulseaudio/core1/playback_stream1"
04-11 11:16:36 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink0
04-11 11:16:36 pulseaudio_dlna.pulseaudio                     INFO     _async_handle_sink_update /org/pulseaudio/core1/sink0 finished!

**Comment by minsonj2016** [comment]
I just realized my issue is with Python2/Master . Sorry

**Comment by minsonj2016** [comment]
Installed but now bombs off with

05-05 11:20:28 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "ccAporch (Chromecast)" to play ...
Traceback (most recent call last):
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/pulseaudio.py", line 773, in _handle_sink_update
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/pulseaudio.py", line 817, in __handle_sink_update
    return_code, message = bridge.device.play(
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/chromecast/renderer.py", line 73, in play
    url = url or self.get_stream_url()
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/renderer.py", line 350, in get_stream_url
    return self._encode_settings(settings, 'stream.' + self.codec.suffix)
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/plugins/renderer.py", line 329, in _encode_settings
    server_ip = pulseaudio_dlna.utils.network.get_host_by_ip(self.ip)
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/utils/network.py", line 50, in get_host_by_ip
    return __pyroute2_get_host_by_ip(ip)
  File "/home/ajminson/Downloads/pulseaudio-dlna-python3/pulseaudio_dlna/utils/network.py", line 69, in __pyroute2_get_host_by_ip
    routes = ipr.get_routes(family=socket.AF_INET, dst=ip)
  File "/usr/lib/python3/dist-packages/pyroute2/iproute/linux.py", line 366, in get_routes
    return self.route('get', dst=kwarg['dst'])
  File "/usr/lib/python3/dist-packages/pyroute2/iproute/linux.py", line 1798, in route
    kwarg = IPRouteRequest(kwarg)
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/rtnl/req.py", line 87, in __init__
    IPRequest.__init__(self, obj)
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/rtnl/req.py", line 29, in __init__
    self.update(obj)
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/rtnl/req.py", line 41, in update
    self[key] = v
  File "/usr/lib/python3/dist-packages/pyroute2/netlink/rtnl/req.py", line 387, in __setitem__
    mask = int(value[1])
ValueError: invalid literal for int() with base 10: '119,192.168.1.154'

**Comment by minsonj2016** [comment]
I downloaded 'zip' from https://github.com/Cygn/pulseaudio-dlna/tree/python3 and did 'make'
This is on Kubuntu Focal Fossa
