### ISSUE TITLE
pulseaudio-dlna doesn't work anymore in Gentoo

### ISSUE THREAD

**Issue by cafaia** [masmu/pulseaudio-dlna#409]
I did these steps:

1 - stop iptables service;

2 - deleted my configuration file 'devices.json';

3 - I ran the command 'pulseaudio-dlna --debug' and none of the devices on the network were detected;

4 - later I executed the command 'pulseaudio-dlna --create-device-config' and all my devices have been detected;

5 - so I ran the command 'pulseaudio-dlna --debug --disable-ssdp-listener' and all my devices have been detected, but I have this error when sending the sound 'ERROR    The device "Blu-ray Disc Player (DLNA)" failed to play! (500) - "Blu-ray Disc Player (DLNA)" : The command "SetAVTransportURI" failed with status code 500!'

[pulseaudio-dlna-debug.txt](https://github.com/masmu/pulseaudio-dlna/files/4977662/pulseaudio-dlna-debug.txt)
[pulseaudio-dlna-create-device-config.txt](https://github.com/masmu/pulseaudio-dlna/files/4977664/pulseaudio-dlna-create-device-config.txt)
[pulseaudio-dlna-ssdp-disable.txt](https://github.com/masmu/pulseaudio-dlna/files/4977666/pulseaudio-dlna-ssdp-disable.txt)

**Comment by cafaia** [comment]
I have these programs as dependent and installed:

eduardo@gentoo ~ $ equery depgraph net-misc/pulseaudio-dlna-0.6.0_pre20200114
 * Searching for pulseaudio-dlna0.6.0_pre20200114 in net-misc ...

 * dependency graph for net-misc/pulseaudio-dlna-0.6.0_pre20200114
 `--  net-misc/pulseaudio-dlna-0.6.0_pre20200114  ~amd64 
   `--  dev-python/protobuf-python-3.11.4  (>=dev-python/protobuf-python-2.5.0) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/docopt-0.6.2-r3  (>=dev-python/docopt-0.6.1) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/requests-2.23.0  (>=dev-python/requests-2.2.1) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/setproctitle-1.1.10-r1  (>=dev-python/setproctitle-1.1.10) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/notify2-0.3.1-r1  (>=dev-python/notify2-0.3) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/psutil-5.7.0  (>=dev-python/psutil-5.4.7) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/chardet-3.0.4  (>=dev-python/chardet-3.0.4) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/pyroute2-0.5.12-r1  (>=dev-python/pyroute2-0.3.5) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/netifaces-0.10.9  (>=dev-python/netifaces-0.10.0) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/lxml-4.5.1  (>=dev-python/lxml-3) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/pychromecast-4.1.0  (>=dev-python/pychromecast-2.3.0) ~amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/pygobject-3.34.0  (dev-python/pygobject) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/dbus-python-1.2.16  (>=dev-python/dbus-python-1.0.0) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  dev-python/zeroconf-0.24.4  (>=dev-python/zeroconf-0.17.4) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  gnome-base/librsvg-2.40.21  (gnome-base/librsvg) amd64  [introspection]
   `--  x11-libs/gtk+-3.24.20  (x11-libs/gtk+) amd64  [introspection]
   `--  media-video/ffmpeg-4.2.4  (media-video/ffmpeg) amd64  [encode fdk mp3 opus vorbis]
   `--  media-libs/faac-1.29.9.2  (media-libs/faac) amd64 
   `--  media-libs/flac-1.3.3  (media-libs/flac) amd64 
   `--  media-sound/lame-3.100-r2  (media-sound/lame) amd64 
   `--  media-sound/opus-tools-0.2  (media-sound/opus-tools) amd64 
   `--  media-sound/sox-14.4.2-r1  (media-sound/sox) amd64 
   `--  media-sound/vorbis-tools-1.4.0-r5  (media-sound/vorbis-tools) amd64 
   `--  dev-python/setuptools-44.1.0  (dev-python/setuptools) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
   `--  media-sound/pulseaudio-13.0  (media-sound/pulseaudio) amd64 
   `--  dev-lang/python-3.6.11-r2  (dev-lang/python) amd64 
   `--  dev-lang/python-3.7.8-r2  (dev-lang/python) amd64 
   `--  dev-lang/python-exec-2.4.6-r1  (>=dev-lang/python-exec-2) amd64  [python_targets_python3_6(-)? python_targets_python3_7(-)? -python_single_target_python3_6(-) -python_single_target_python3_7(-)]
[ net-misc/pulseaudio-dlna-0.6.0_pre20200114 stats: packages (29), max depth (1) ]

**Comment by happysmash27** [comment]
I get a completely different set of errors on my Gentoo box. I cannot disable iptables, as this device also acts as a router with a custom iptables config, and I'm not sure if that makes a difference here or not. 

The device I *want* it to play on, a Sonos soundbar, is detected, and successfully put into the config, but for some reason will not show up in Pavucontrol. 

One device that *does* show up in pavucontrol is the Android TV, however, which gives a different error which I'm guessing is the fault of unstable APIs: 

```
10-03 12:14:34 pulseaudio_dlna.pulseaudio                     INFO     Instructing the device "Living Room TV (Chromecast)" to play ...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 773, in _handle_sink_update
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 818, in __handle_sink_update
    artist=artist, title=title, thumb=thumb)
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/plugins/chromecast/renderer.py", line 72, in play
    url = url or self.get_stream_url()
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/plugins/renderer.py", line 350, in get_stream_url
    return self._encode_settings(settings, 'stream.' + self.codec.suffix)
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/plugins/renderer.py", line 329, in _encode_settings
    server_ip = pulseaudio_dlna.utils.network.get_host_by_ip(self.ip)
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/utils/network.py", line 50, in get_host_by_ip
    return __pyroute2_get_host_by_ip(ip)
  File "/usr/lib/python3.7/site-packages/pulseaudio_dlna/utils/network.py", line 69, in __pyroute2_get_host_by_ip
    routes = ipr.get_routes(family=socket.AF_INET, dst=ip)
  File "/usr/lib/python3.7/site-packages/pyroute2/iproute/linux.py", line 370, in get_routes
    return self.route('get', dst=kwarg['dst'])
  File "/usr/lib/python3.7/site-packages/pyroute2/iproute/linux.py", line 1821, in route
    kwarg = IPRouteRequest(kwarg)
  File "/usr/lib/python3.7/site-packages/pyroute2/netlink/rtnl/req.py", line 88, in __init__
    IPRequest.__init__(self, obj)
  File "/usr/lib/python3.7/site-packages/pyroute2/netlink/rtnl/req.py", line 30, in __init__
    self.update(obj)
  File "/usr/lib/python3.7/site-packages/pyroute2/netlink/rtnl/req.py", line 42, in update
    self[key] = v
  File "/usr/lib/python3.7/site-packages/pyroute2/netlink/rtnl/req.py", line 390, in __setitem__
    mask = int(value[1])
ValueError: invalid literal for int() with base 10: '119,192.168.1.114'
```

Maybe re-emerging pyroute2 will work. I already had to re-emerge protocol-buffers to get pulseaudio-dlna to even generate the configs. 

...That didn't work either. 

Emerging /usr/lib/python3.7/concurrent/futures/thread.py, which emerges python-3.7.9, also changes nothing.

**Comment by cafaia** [comment]
Hello, happysmash27!

I am sorry that you also have errors in the program, I hope someone can help us!
With best regards!
