### ISSUE TITLE
No module named 'utils.git'

### ISSUE THREAD

**Issue by Uberseer** [masmu/pulseaudio-dlna#433]
I just downloaded this project and built it using "pip3 install ."  No errors were reported, so I tried to run pulseaudio-dlna but I see the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pulseaudio-dlna", line 5, in <module>
    from pulseaudio_dlna.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/pulseaudio_dlna/__init__.py", line 23, in <module>
    import utils.git
ModuleNotFoundError: No module named 'utils'
```

I'm running almalinux 9, and I know very little about Python.   I tried the obvious "pip3 install utils" and that seemed to work, but next time I ran pulseaudio-dlna it says

```
  File "/usr/local/bin/pulseaudio-dlna", line 5, in <module>
    from pulseaudio_dlna.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/pulseaudio_dlna/__init__.py", line 23, in <module>
    import utils.git
ModuleNotFoundError: No module named 'utils.git'
```

And I can't figure out how to solve that one.  This doesn't seem to be a standard python3 library (according to search engine)...how do I get and install this?  Or am I on the wrong path?  My installation and run steps are:

```
git clone https://github.com/masmu/pulseaudio-dlna.git
cd pulseaudio-dlna
pip3 install .
pulseaudio-dlna
```

**Comment by Uberseer** [comment]
I tried installing again, this time using "make install".  (But first I modified the python variable to equal python3).  It did a lot of things :)) But, when I run pulseaudio-dlna I get a similar error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pulseaudio-dlna", line 33, in <module>
    sys.exit(load_entry_point('pulseaudio-dlna==0.5.2', 'console_scripts', 'pulseaudio-dlna')())
  File "/usr/local/bin/pulseaudio-dlna", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/pulseaudio_dlna/__init__.py", line 23, in <module>
    import utils.git
ModuleNotFoundError: No module named 'utils.git'

```

**Comment by Uberseer** [comment]
Learning more about python, I realize now that utils/git.py is being imported.  I unzipped the .egg file and that git.py exists.  I discovered that if I set the python path like this:

` export PYTHONPATH=/usr/local/pulseaudio-dlna/pulseaudio_dlna`

I get past the error, but then onto the next error

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = '/usr/local/pulseaudio-dlna/pulseaudio_dlna'
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib64'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/local/pulseaudio-dlna/pulseaudio_dlna',
    '/usr/lib64/python39.zip',
    '/usr/lib64/python3.9',
    '/usr/lib64/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "/usr/lib64/python3.9/encodings/__init__.py", line 31, in <module>
  File "/usr/local/pulseaudio-dlna/pulseaudio_dlna/codecs.py", line 21, in <module>
  File "/usr/lib64/python3.9/logging/__init__.py", line 26, in <module>
  File "/usr/lib64/python3.9/traceback.py", line 5, in <module>
  File "/usr/lib64/python3.9/linecache.py", line 11, in <module>
  File "/usr/lib64/python3.9/tokenize.py", line 27, in <module>
ImportError: cannot import name 'open' from 'builtins' (unknown location)

```

I'm stumbling my way through this, but something seems wrong at a fundamental level.

**Comment by Uberseer** [comment]
Just realized code is not python3 compatible...so I won't be able to get it running anyways.
