### ISSUE TITLE
Startup from network manager dispatcher fails

### ISSUE THREAD

**Issue by Lahorde** [masmu/pulseaudio-dlna#52]
Hi,

I'm starting pulseaudio-dlna using NetworkManager dispatcher : https://wiki.archlinux.org/index.php/NetworkManager#Network_services_with_NetworkManager_dispatcher
when connection is up / down it executes scripts in a given directory. 

In order to connect to existing dbus session I launch pulseaudio-dlna with such commands (in a bash script):
    
    pid=`pidof pulseaudio` 
    user=`ps -p $pid -o user=`
    export `strings /proc/$pid/environ | grep DBUS_SESSION_BUS_ADDRESS`
    sudo -E -u $user pulseaudio-dlna --debug 

I get some errors :
   
    pa_context_connect() has failed: Connection refused

It cannot connect to dbus session daemon. When I execute same script from a terminal pulseaudio-dlna starts gently. 
I found some interesting posts about connection from root to user dbus session :
http://lists.freedesktop.org/archives/dbus/2010-May/012766.html
I checked uid and DBUS_SESSION_BUS_ADDRESS  was correctly set when some pactl subrpocesses are spawn but it does not help.

Have I missed something? Have you got some suggestions?

lah

**Comment by masmu** [comment]
Currently i am doing something quite similar.

There are more environment variables than DBUS_SESSION_BUS_ADDRESS which are necessary for what you are doing.
But i am not sure which of them are necessary. I am using the complete environment of the process to steal the DBUS_SESSION_BUS_ADDRESS from.

```python
DBUS_SESSION_BUS_REGEX = (
    r'dbus-daemon.*address=(unix:abstract=/tmp/dbus-[A-Za-z0-9]{10})')

def find_session_bus_env(pid):
    for proc in psutil.process_iter():
        if proc.uids[0] == pid and proc.name == 'dbus-daemon':
            match = re.findall(DBUS_SESSION_BUS_REGEX, str(proc.cmdline))
            if match:
                return _get_proc_env(proc.pid)
    return None


def _get_proc_env(pid):
    env = {}
    location = '/proc/{pid}/environ'.format(pid=pid)
    with open(location) as f:
        content = f.read()
    for line in content.split('\0'):
        try:
            key, value = line.split('=', 1)
            env[key] = value
        except ValueError:
            pass
    return env

env = find_session_bus_env(1000)
process = UserMultiProcess(target=test, uid=1000, gid=1000, env=env)
```

If you find out which variables are needed exactly, let me know! :+1:

**Comment by Lahorde** [comment]
I got it working adding XDG_RUNTIME_DIR !

```
function find_dlna_devices()
{
    # DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR must be set in order to be able to connect user to dbus from root
    # needed by pulseaudio_dlna
    while ! pid=$(pidof pulseaudio) ; do
        sleep 2
    done
    #pulseaudio starts several times, take first daemon
    pid=$(awk -F " " '{print $1}' <<< $pid)
    user=`ps -p $pid -o user=`
    export `strings /proc/$pid/environ | grep DBUS_SESSION_BUS_ADDRESS`
    export `strings /proc/$pid/environ | grep XDG_RUNTIME_DIR`

    if [ -n $1 ] ; then
        renderer_arg="--renderer-urls=$1"
    fi
    stdbuf -i0 -o0 -e0 su $user -c "pulseaudio-dlna $renderer_arg"
    echo  "pulseaudio dlna stopped with code $?"
}
```

**Comment by masmu** [comment]
Thanks for your feedback!

Yesterday it worked without _XDG_RUNTIME_DIR_. Today it stopped working (and i did not change the code) and after adding it, it was working again.

I also had to add _DISPLAY_. Could you check if there are more than one pulseaudio instances running?
I had this odd situation where the starting of _pulseaudio-dlna_ made the system start a second pulseaudio instance.

**Comment by Lahorde** [comment]
After pulseaudio-dlna I have a single pulseaudio process :

    ps -ax |grep pulseaudio
     4173 ?        S<l    0:17 /usr/bin/pulseaudio --start --log-target=syslog
     4264 ?        S      0:00 su remi -c pulseaudio-dlna 
     4265 ?        Ss     0:00 pulseaudio-dlna

But during startup, before pulseaudio-dlna is launched, 

    pidof pulseaudio

can return several pid, that's why I've added 

    #pulseaudio starts several times, take first daemon
    pid=$(awk -F " " '{print $1}' <<< $pid)

**Comment by masmu** [comment]
I just release _0.4.0_ and since that version it is possible to run the application as root. No additional hacks necessary. Btw: I ended up in using:
- DISPLAY
- DBUS_SESSION_BUS_ADDRESS
- XDG_RUNTIME_DIR

Tests and bugs welcome! :+1:

**Comment by Lahorde** [comment]
I got some new errors when starting pulseaudio-dlna from NetworkManager dispatcher :

```
12-13 22:29:48 pulseaudio_dlna.application                    INFO     Using version: 0.4.6
12-13 22:29:48 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.1.90:8080
12-13 22:29:48 pulseaudio_dlna.application                    INFO     Encoder settings:
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <AacEncoder available="True" bit-rate="192">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <FlacEncoder available="True">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <L16Encoder available="False" sample-rate="44100" channels="2">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <LameEncoder available="True" bit-rate="192">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <OggEncoder available="False" bit-rate="192">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <OpusEncoder available="False" bit-rate="192">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <WavEncoder available="False">
12-13 22:29:48 pulseaudio_dlna.application                    INFO     Codec settings:
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav">
12-13 22:29:48 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg">
12-13 22:29:56 pulseaudio_dlna.listener                       INFO     Discovery complete.
12-13 22:29:56 pulseaudio_dlna.pulseaudio                     INFO     Could not get default sink. Perhaps there is no one set?
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 433, in run
    self._connect(signals)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 72, in _connect
    sink = PulseSinkFactory.new(self.bus, sink_path)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 242, in new
    label = self._convert_bytes_to_unicode(description_bytes)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/pulseaudio.py", line 264, in _convert_bytes_to_unicode
    return name.decode(locale.getpreferredencoding())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
```

I solved it exporting LANG variable in bash function calling pulseaudio-dlna that is called by root user. 

```
function find_dlna_devices()
{
    #some DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR must be set in order to be able to connect user to dbus from root
    # needed by pulseaudio_dlna
    while ! pid=$(pidof pulseaudio) ; do
        sleep 2
    done
    #pulseaudio starts several times, take first daemon
    pid=$(awk -F " " '{print $1}' <<< $pid)
    user=`ps -p $pid -o user=`
    export `strings /proc/$pid/environ | grep DBUS_SESSION_BUS_ADDRESS`
    export `strings /proc/$pid/environ | grep XDG_RUNTIME_DIR`
    export `strings /proc/$pid/environ | grep LANG`

    if [ -n "$1" ] ; then
        renderer_arg="--renderer-urls=$1"
    fi
    stdbuf -i0 -o0 -e0 su $user -c "pulseaudio-dlna $renderer_arg"
    echo  "pulseaudio dlna stopped with code $?"
}
```
