### ISSUE TITLE
pulseaudio-dlna crashes with WML11B on network

### ISSUE THREAD

**Issue by parkerlreed** [masmu/pulseaudio-dlna#94]
When my WML11B is on the network it crashes out. If I unplug it finishes discovery just fine.

Arch x86_64

````
[parker@x3720 ~]$ pulseaudio-dlna 
09-24 20:39:19 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
09-24 20:39:19 pulseaudio_dlna.application                    INFO     Using version: 0.4.5.2
09-24 20:39:19 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.1.233:8080
09-24 20:39:19 pulseaudio_dlna.application                    INFO     Encoder settings:
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <AacEncoder available="True" bit-rate="192">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <FlacEncoder available="True">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <L16Encoder available="True" sample-rate="44100" channels="2">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <LameEncoder available="True" bit-rate="192">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <OggEncoder available="True" bit-rate="192">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <OpusEncoder available="True" bit-rate="192">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <WavEncoder available="True">
09-24 20:39:19 pulseaudio_dlna.application                    INFO     Codec settings:
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav">
09-24 20:39:19 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg">
Traceback (most recent call last):
  File "/usr/bin/pulseaudio-dlna", line 9, in <module>
    load_entry_point('pulseaudio-dlna==0.4.5.2', 'console_scripts', 'pulseaudio-dlna')()
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/__main__.py", line 117, in main
    app.run(options)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/application.py", line 194, in run
    device_filter, device_config, locations, disable_ssdp_listener)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/listener.py", line 71, in __init__
    discover.search()
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/discover.py", line 69, in search
    BaseUpnpMediaRendererDiscover.search(self, ttl, timeout, times)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/discover.py", line 53, in search
    self._header_received(header.decode(guess['encoding']), address)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/discover.py", line 74, in _header_received
    self.renderer_holder.add_from_search(header)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/renderers.py", line 106, in add_from_search
    self._add_renderer_with_filter_check(device_id, device)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/renderers.py", line 68, in _add_renderer_with_filter_check
    self._add_renderer(device_id, device)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/renderers.py", line 75, in _add_renderer
    device.activate(config)
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/plugins/upnp/renderer.py", line 160, in activate
    self.get_protocol_info()
  File "/usr/lib/python2.7/site-packages/pulseaudio_dlna/plugins/upnp/renderer.py", line 239, in get_protocol_info
    url = self.service_connection.control_url
AttributeError: 'NoneType' object has no attribute 'control_url
````

**Comment by masmu** [comment]
Could you uninstall _pulseaudio-dlna_, checkout [bug/no-control-url](https://github.com/masmu/pulseaudio-dlna/tree/bug/no-control-url), `make`, `bin/pulseaudio-dlna` and check if the bug has been fixed?

**Comment by parkerlreed** [comment]
````
[parker@x3720 pulseaudio-dlna]$ git checkout -b bug/no-control-url
Switched to a new branch 'bug/no-control-url'
[parker@x3720 pulseaudio-dlna]$ make
virtualenv --system-site-packages -p python2.7 .
Running virtualenv with interpreter /usr/bin/python2.7
...
[parker@x3720 pulseaudio-dlna]$ bin/pulseaudio-dlna 
09-25 19:34:52 pulseaudio_dlna.notification                   ERROR    notify2 could not be initialized! Notifications will most likely not work.
09-25 19:34:52 pulseaudio_dlna.application                    INFO     Using version: 0.4.5.2
09-25 19:34:52 pulseaudio_dlna.application                    INFO     Using localhost: 192.168.1.233:8080
09-25 19:34:52 pulseaudio_dlna.application                    INFO     Encoder settings:
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <AacEncoder available="True" bit-rate="192">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <FlacEncoder available="True">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <L16Encoder available="True" sample-rate="44100" channels="2">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <LameEncoder available="True" bit-rate="192">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <NullEncoder available="True">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <OggEncoder available="True" bit-rate="192">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <OpusEncoder available="True" bit-rate="192">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <WavEncoder available="True">
09-25 19:34:52 pulseaudio_dlna.application                    INFO     Codec settings:
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <AacCodec enabled="True" priority="12" mime_type="audio/aac">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <L16Codec enabled="True" priority="0" mime_type="audio/L16">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <OpusCodec enabled="True" priority="3" mime_type="audio/opus">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <Mp3Codec enabled="True" priority="18" mime_type="audio/mp3">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <FlacCodec enabled="True" priority="9" mime_type="audio/flac">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <WavCodec enabled="True" priority="15" mime_type="audio/wav">
09-25 19:34:52 pulseaudio_dlna.application                    INFO       <OggCodec enabled="True" priority="6" mime_type="audio/ogg">
Traceback (most recent call last):
  File "bin/pulseaudio-dlna", line 9, in <module>
    load_entry_point('pulseaudio-dlna==0.4.5.2', 'console_scripts', 'pulseaudio-dlna')()
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/__main__.py", line 117, in main
    app.run(options)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/application.py", line 194, in run
    device_filter, device_config, locations, disable_ssdp_listener)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/listener.py", line 71, in __init__
    discover.search()
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/discover.py", line 69, in search
    BaseUpnpMediaRendererDiscover.search(self, ttl, timeout, times)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/discover.py", line 53, in search
    self._header_received(header.decode(guess['encoding']), address)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/discover.py", line 74, in _header_received
    self.renderer_holder.add_from_search(header)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/renderers.py", line 106, in add_from_search
    self._add_renderer_with_filter_check(device_id, device)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/renderers.py", line 68, in _add_renderer_with_filter_check
    self._add_renderer(device_id, device)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/renderers.py", line 75, in _add_renderer
    device.activate(config)
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/plugins/upnp/renderer.py", line 160, in activate
    self.get_protocol_info()
  File "/home/parker/build/pulseaudio-dlna/pulseaudio_dlna/plugins/upnp/renderer.py", line 239, in get_protocol_info
    url = self.service_connection.control_url
AttributeError: 'NoneType' object has no attribute 'control_url'
````

It's on a bridge connected to the main network if that affects it.

**Comment by masmu** [comment]
I guess you did not checkout the correct branch. In that branch there is no method called `add_from_search` any more.

**Comment by parkerlreed** [comment]
I did 

````
git clone https://github.com/masmu/pulseaudio-dlna.git
cd pulseaudio-dlna
git checkout -b bug/no-control-url
````

From what I see that's all that is needed.

**Comment by masmu** [comment]
That sounds right. Did you uninstall a previous version? I assume the modules of the installed version are loaded, because in your traceback there is definitely running the wrong code.

**Comment by parkerlreed** [comment]
Yeah previous version was the AUR package. I removed that and then compiled this. All the paths in the error point to my local build directory.

**Comment by masmu** [comment]
Could you search for the method `add_from_search` in your local installation? It should not be there ... the method is now named `process_msearch_request`.

**Comment by masmu** [comment]
Oh i just saw that you used the `-b` flag for checking out the branch. But this flags creates a branch.
The correct way would be just `git checkout bug/no-control-url`. That's why you did not receive the changes :wink:

**Comment by parkerlreed** [comment]
Do I need to disable SSDP?

````
09-26 19:26:03 pulseaudio_dlna.application                    ERROR    The SSDP listener could not bind to the port 1900/UDP. Probably the port is in use by another application. Terminate the application which is using the port or run this application with the "--disable-ssdp-listener" flag.
````

I get that every time it tries to discover.

**Comment by masmu** [comment]
It seems as the port is already bound. So, yes.

**Comment by parkerlreed** [comment]
Oh Plex is running :) 

Stopped Plex and I get this

````
09-26 19:30:42 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "Linksys WML11B (DLNA)" does not specify a service transport url. Device skipped!
09-26 19:30:42 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "Linksys WML11B (DLNA)" does not specify a service transport url. Device skipped!
09-26 19:30:42 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "Linksys WML11B (DLNA)" does not specify a service transport url. Device skipped!
09-26 19:30:42 pulseaudio_dlna.plugins.upnp.renderer          INFO     The device "Linksys WML11B (DLNA)" does not specify a service transport url. Device skipped!
09-26 19:30:47 pulseaudio_dlna.listener                       INFO     Discovery complete.
````

So do I just need to manually setup the WML11B?

**Comment by masmu** [comment]
Devices which do not specify a service transport url cannot be controlled remotely, AFAIK. Is there another application which can send streams to that device? Or can you just access other DLNA Servers from that device?

**Comment by parkerlreed** [comment]
I can access DLNA devices from the device but come to think of it I don't think I ever tried it as a sink. It probably doesn't even support it. Ugh oh well. Thanks for the help.

**Comment by masmu** [comment]
You are welcome!

Try it with other applications, such as _Bubble-UPnP_ if you own an Android phone. If they fail too, it is pretty sure the device does not support it.

**Comment by parkerlreed** [comment]
Wow good timing. I just installed BubbleUPnP again. Works really well. Thanks for this project!

**Comment by masmu** [comment]
What works well? _pulseaudio-dlna_ and _Bubble-UPnP_ or _Bubble-UPnP_ and your device?

**Comment by parkerlreed** [comment]
Pulseaudio-DLNA with BubbleUPnP :) Come to think of it I have used BubbleUPnP in the past as a server and played stuff on the WML11B. Fairly old Internet radio player but still kicking.

**Comment by masmu** [comment]
Try to stream to your device with _BubbleUPnP_ without touching your device. If that works, it is capable of being remote controlled.

**Comment by parkerlreed** [comment]
Yeah the WML11B doesn't show up as a renderer.

**Comment by masmu** [comment]
So, i am sorry. Then your device simply does not support it :cry:

**Comment by masmu** [comment]
If your device does have a line-in jack you can "extend" it with a device like the _D-Link DCH-M225/E_. It is pretty cheap and works well. Connect the line jack from the _D-Link_ with the line-in of your device and you have that feature you are looking for.
